# Copyright (C) 2023 by University of Luxembourg

# Summary
#
# This is a file which describes CI/CD pipeline for Shinyscreen. The
# main goal is to test Shinyscreen and create appropriately versioned
# Docker images on whichever container registry is used.
#
# There are three stages: _build_, _test_ and _release_. Jobs
# associated with build and test stages should run an all
# commits. Release jobs run exclusively on tagged commits of vX.Y.Z 
# format.
#
# Job tags _docker_ and _$RUNNER_TAG_ serve to inform GitLab which
# gitlab-runners (programs which perform jobs) are suitable to pick up
# the pipeline.
#
# The pipeline itself is following the paradigm of docker-in-docker
# build. In short, it helps having reproducible builds and
# tests. There is more documentation available online.


image: docker:23.0.1
services:
  - docker:23.0.1-dind

stages:
  - dep_images
  - build
  - test
  - release

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DEP_ROOT: $CI_REGISTRY_IMAGE/dep
  BASE_IMAGE: $CI_REGISTRY_IMAGE/dep/base:latest
  SSUSER_IMAGE: $CI_REGISTRY_IMAGE/dep/ssuser:latest
  ISB401_BASE_IMAGE: $CI_REGISTRY_IMAGE/dep/isb401_base:latest
  TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  ISB401_TEST_IMAGE: $CI_REGISTRY_IMAGE:isb401_$CI_COMMIT_REF_SLUG
  ISB401_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:isb401_$CI_COMMIT_TAG



base-image:
  tags:
    - docker
    - $RUNNER_TAG
  stage: dep_images
  rules:
    - if: $CI_COMMIT_TAG == ""
      changes:
        - docker/base/Dockerfile
  script:
    - cd docker/base
    - docker build --pull -t $BASE_IMAGE .
    - docker push $BASE_IMAGE

ssuser-image:
  tags:
    - docker
    - $RUNNER_TAG
  stage: dep_images
  needs:
    - job: base-image
      optional: true
  rules:
    - if: $CI_COMMIT_TAG == ""
      changes:
        - docker/ssuser/Dockerfile
  script:
    - cd docker/ssuser
    - docker build --pull -t $SSUSER_IMAGE .
    - docker push $SSUSER_IMAGE

isb401-base-image:
  tags:
    - docker
    - $RUNNER_TAG
  stage: dep_images
  needs:
    - job: ssuser-image
      optional: true
  rules:
    - if: $CI_COMMIT_TAG == ""
      changes:
        - docker/isb401_base/Dockerfile
  script:
    - cd docker/isb401_base
    - docker build --pull -t $ISB401_BASE_IMAGE .
    - docker push $ISB401_BASE_IMAGE


build:
  tags:
    - docker
    - $RUNNER_TAG
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

build-isb401:
  tags:
    - docker
    - $RUNNER_TAG
  stage: build
  needs:
    - job: build
  script:
    - cp docker/isb401/Dockerfile .
    - docker build --pull -t $ISB401_TEST_IMAGE .
    - docker push $ISB401_TEST_IMAGE

test:
  tags:
    - docker
    - $RUNNER_TAG
  stage: test
  script:
    - docker pull $TEST_IMAGE
    - docker run $TEST_IMAGE test

test-isb401:
  tags:
    - docker
    - $RUNNER_TAG
  stage: test
  script:
    - docker pull $ISB401_TEST_IMAGE
    - docker run $ISB401_TEST_IMAGE test

release-image:
  tags:
    - docker
    - $RUNNER_TAG
  stage: release
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+.[0-9]+.[0-9]+/

release-isb401:
  tags:
    - docker
    - $RUNNER_TAG
  stage: release
  script:
    - docker pull $ISB401_TEST_IMAGE
    - docker tag $ISB401_TEST_IMAGE $ISB401_RELEASE_IMAGE
    - docker push $ISB401_RELEASE_IMAGE
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+.[0-9]+.[0-9]+/

